# Generated by Django 2.0.3 on 2019-01-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.CharField(max_length=250)),
                ('staticid', models.CharField(max_length=250)),
                ('qid', models.CharField(max_length=250)),
                ('question', models.TextField()),
                ('a', models.CharField(max_length=250)),
                ('b', models.CharField(max_length=250)),
                ('c', models.CharField(max_length=250)),
                ('d', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='LOW', max_length=6)),
                ('complexity', models.PositiveIntegerField(default=0)),
                ('time', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('foundation', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('core', models.CharField(max_length=250)),
                ('exam', models.CharField(max_length=250)),
                ('fscore', models.CharField(max_length=250)),
                ('sscore', models.CharField(max_length=250)),
                ('cscore', models.CharField(max_length=250)),
                ('escore', models.CharField(max_length=250)),
            ],
        ),
    ]
