# Generated by Django 2.0.3 on 2019-01-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='staticid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
