# Generated by Django 2.0.3 on 2019-01-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0003_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
