# Generated by Django 2.0.3 on 2019-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0004_delete_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staticid', models.IntegerField()),
                ('sub_topic', models.CharField(max_length=250)),
                ('Num_Of_Sub_subTopics', models.PositiveIntegerField(default=0)),
                ('Num_Of_Questions', models.PositiveIntegerField(default=0)),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='LOW', max_length=6)),
                ('complexity', models.PositiveIntegerField(default=0)),
                ('prerequisite', models.CharField(max_length=250)),
            ],
        ),
    ]
